name: Publish to pub.dev

## Caller of this workflow should use it as follows:
## jobs:
##   publish:
##     uses: dart-lang/setup-dart/.github/workflows/publish.yml@main [or a recent commit hash / version tag]
##     # with:
##     #   working-directory: path/to/sub/directory

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    name: 'Publish to pub.dev'
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write # This is required for requesting the JWT
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v4
      # Setup Dart SDK with JWT token
      - uses: dart-lang/setup-dart@8a4b97ea2017cc079571daec46542f76189836b1
      # Minimal package setup and dry run checks.
      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ inputs.working-directory }}
      - name: Publish - dry run
        run: flutter pub publish --dry-run
        working-directory: ${{ inputs.working-directory }}
      # Publishing...
      - name: Publish to pub.dev
        run: flutter pub publish -f
        working-directory: ${{ inputs.working-directory }}
